export const URL_MAPPINGS: Record<string, string> = {
  // Video & Streaming
  'youtube.com': 'YouTube',
  'youtu.be': 'YouTube',
  'netflix.com': 'Netflix',
  'primevideo.com': 'Amazon Prime Video',
  'amazon.com/prime-video': 'Amazon Prime Video',
  'hotstar.com': 'Disney+ Hotstar',
  'disneyplus.com': 'Disney+',
  'hulu.com': 'Hulu',
  'hbomax.com': 'HBO Max',
  'max.com': 'Max',
  'peacocktv.com': 'Peacock',
  'twitch.tv': 'Twitch',
  'vimeo.com': 'Vimeo',
  'dailymotion.com': 'Dailymotion',
  'zee5.com': 'ZEE5',
  'sonyliv.com': 'SonyLIV',
  'jiocinema.com': 'JioCinema',
  'mxplayer.in': 'MX Player',
  'crunchyroll.com': 'Crunchyroll',
  'funimation.com': 'Funimation',
  'tiktok.com': 'TikTok',
  'bilibili.com': 'Bilibili',
  'iqiyi.com': 'iQIYI',
  'youku.com': 'Youku',
  'tudou.com': 'Tudou',
  'pluto.tv': 'Pluto TV',
  'tubi.tv': 'Tubi',
  'roku.com': 'Roku',
  'sling.com': 'Sling TV',
  'fubo.tv': 'FuboTV',
  'espn.com': 'ESPN',
  'espnplus.com': 'ESPN+',
  'dazn.com': 'DAZN',
  'paramount.com': 'Paramount+',
  'paramountplus.com': 'Paramount+',
  'apple.com/tv': 'Apple TV+',
  'tv.apple.com': 'Apple TV+',
  'discoveryplus.com': 'Discovery+',
  'curiositystream.com': 'CuriosityStream',
  'masterclass.com': 'MasterClass',
  'skillshare.com': 'Skillshare',

  // Social Media
  'facebook.com': 'Facebook',
  'fb.com': 'Facebook',
  'instagram.com': 'Instagram',
  'twitter.com': 'Twitter/X',
  'x.com': 'X (Twitter)',
  'linkedin.com': 'LinkedIn',
  'pinterest.com': 'Pinterest',
  'snapchat.com': 'Snapchat',
  'reddit.com': 'Reddit',
  'tumblr.com': 'Tumblr',
  'quora.com': 'Quora',
  'discord.com': 'Discord',
  'discordapp.com': 'Discord',
  'slack.com': 'Slack',
  'telegram.org': 'Telegram',
  'web.telegram.org': 'Telegram',
  'signal.org': 'Signal',
  'threads.net': 'Threads',
  'mastodon.social': 'Mastodon',
  'bsky.app': 'Bluesky',
  'weibo.com': 'Weibo',
  'wechat.com': 'WeChat',
  'line.me': 'LINE',
  'viber.com': 'Viber',
  'clubhouse.com': 'Clubhouse',
  'meetup.com': 'Meetup',
  'nextdoor.com': 'Nextdoor',
  'myspace.com': 'MySpace',
  'vk.com': 'VK',
  'ok.ru': 'Odnoklassniki',
  'taringa.net': 'Taringa!',
  'parler.com': 'Parler',
  'gab.com': 'Gab',
  'gettr.com': 'GETTR',
  'truthsocial.com': 'Truth Social',

  // Messaging & Communication
  'whatsapp.com': 'WhatsApp',
  'web.whatsapp.com': 'WhatsApp Web',
  'messenger.com': 'Facebook Messenger',
  'hangouts.google.com': 'Google Hangouts',
  'meet.google.com': 'Google Meet',
  'zoom.us': 'Zoom',
  'teams.microsoft.com': 'Microsoft Teams',
  'skype.com': 'Skype',
  'whereby.com': 'Whereby',
  'webex.com': 'Cisco Webex',
  'gotomeeting.com': 'GoToMeeting',
  'bluejeans.com': 'BlueJeans',
  'chime.aws': 'Amazon Chime',
  'loom.com': 'Loom',
  'around.co': 'Around',
  'gather.town': 'Gather',
  'tandem.chat': 'Tandem',
  'krisp.ai': 'Krisp',
  'otter.ai': 'Otter.ai',
  'mmhmm.app': 'mmhmm',

  // AI Tools
  'chat.openai.com': 'ChatGPT',
  'openai.com': 'OpenAI',
  'chatgpt.com': 'ChatGPT',
  'gemini.google.com': 'Google Gemini',
  'bard.google.com': 'Google Gemini',
  'claude.ai': 'Claude AI',
  'anthropic.com': 'Anthropic',
  'perplexity.ai': 'Perplexity AI',
  'poe.com': 'Poe',
  'character.ai': 'Character.AI',
  'jasper.ai': 'Jasper AI',
  'copy.ai': 'Copy.ai',
  'writesonic.com': 'Writesonic',
  'rytr.me': 'Rytr',
  'grammarly.com': 'Grammarly',
  'quillbot.com': 'QuillBot',
  'wordtune.com': 'Wordtune',
  'notion.ai': 'Notion AI',
  'coda.io': 'Coda',
  'gamma.app': 'Gamma',
  'tome.app': 'Tome',
  'beautiful.ai': 'Beautiful.ai',
  'designs.ai': 'Designs.ai',
  'canva.com/magic': 'Canva Magic',
  'midjourney.com': 'Midjourney',
  'leonardo.ai': 'Leonardo AI',
  'stability.ai': 'Stability AI',
  'runwayml.com': 'Runway ML',
  'descript.com': 'Descript',
  'elevenlabs.io': 'ElevenLabs',
  'murf.ai': 'Murf AI',
  'synthesia.io': 'Synthesia',
  'pictory.ai': 'Pictory',
  'lumen5.com': 'Lumen5',
  'invideo.io': 'InVideo',
  'kapwing.com': 'Kapwing',
  'replika.ai': 'Replika',
  'you.com': 'You.com',
  'neeva.com': 'Neeva',
  'bing.com/chat': 'Bing Chat',
  'copilot.microsoft.com': 'Microsoft Copilot',
  'github.copilot': 'GitHub Copilot',
  'phind.com': 'Phind',
  'huggingface.co': 'Hugging Face',
  'cohere.ai': 'Cohere',
  'ai21.com': 'AI21 Labs',
  'deepl.com': 'DeepL',
  'papago.naver.com': 'Papago',

  // Search Engines
  'google.com': 'Google',
  'google.co.in': 'Google India',
  'google.co.uk': 'Google UK',
  'bing.com': 'Bing',
  'yahoo.com': 'Yahoo',
  'duckduckgo.com': 'DuckDuckGo',
  'baidu.com': 'Baidu',
  'yandex.com': 'Yandex',
  'ecosia.org': 'Ecosia',
  'brave.com/search': 'Brave Search',
  'startpage.com': 'Startpage',
  'qwant.com': 'Qwant',
  'wolframalpha.com': 'Wolfram Alpha',
  'ask.com': 'Ask.com',
  'aol.com': 'AOL',
  'naver.com': 'Naver',
  'sogou.com': 'Sogou',
  'so.com': '360 Search',

  // Email Services
  'gmail.com': 'Gmail',
  'mail.google.com': 'Gmail',
  'outlook.com': 'Outlook',
  'outlook.live.com': 'Outlook',
  'outlook.office.com': 'Outlook',
  'office365.com': 'Microsoft 365',
  'yahoo.com/mail': 'Yahoo Mail',
  'mail.yahoo.com': 'Yahoo Mail',
  'protonmail.com': 'ProtonMail',
  'proton.me': 'Proton Mail',
  'zoho.com/mail': 'Zoho Mail',
  'mail.zoho.com': 'Zoho Mail',
  'aol.com/mail': 'AOL Mail',
  'icloud.com': 'iCloud Mail',
  'tutanota.com': 'Tutanota',
  'fastmail.com': 'Fastmail',
  'hey.com': 'HEY',
  'gmx.com': 'GMX Mail',
  'mail.com': 'Mail.com',
  'yandex.com/mail': 'Yandex Mail',
  'rediffmail.com': 'Rediffmail',
  'mailchimp.com': 'Mailchimp',
  'constantcontact.com': 'Constant Contact',
  'sendinblue.com': 'Sendinblue',
  'sendgrid.com': 'SendGrid',
  'mailgun.com': 'Mailgun',
  'postmarkapp.com': 'Postmark',
  'sparkpost.com': 'SparkPost',

  // Google Services
  'drive.google.com': 'Google Drive',
  'docs.google.com': 'Google Docs',
  'sheets.google.com': 'Google Sheets',
  'slides.google.com': 'Google Slides',
  'forms.google.com': 'Google Forms',
  'calendar.google.com': 'Google Calendar',
  'photos.google.com': 'Google Photos',
  'maps.google.com': 'Google Maps',
  'translate.google.com': 'Google Translate',
  'news.google.com': 'Google News',
  'play.google.com': 'Google Play Store',
  'keep.google.com': 'Google Keep',
  'contacts.google.com': 'Google Contacts',
  'earth.google.com': 'Google Earth',
  'classroom.google.com': 'Google Classroom',
  'sites.google.com': 'Google Sites',
  'cloud.google.com': 'Google Cloud',
  'console.cloud.google.com': 'Google Cloud Console',
  'analytics.google.com': 'Google Analytics',
  'ads.google.com': 'Google Ads',
  'adsense.google.com': 'Google AdSense',
  'trends.google.com': 'Google Trends',
  'fonts.google.com': 'Google Fonts',
  'developer.google.com': 'Google Developers',
  'firebase.google.com': 'Firebase',
  'colab.research.google.com': 'Google Colab',
  'kaggle.com': 'Kaggle',
  'blogger.com': 'Blogger',
  'feedburner.google.com': 'FeedBurner',

  // Microsoft Services
  'microsoft.com': 'Microsoft',
  'office.com': 'Microsoft Office',
  'microsoft365.com': 'Microsoft 365',
  'onedrive.com': 'OneDrive',
  'onedrive.live.com': 'OneDrive',
  'sharepoint.com': 'SharePoint',
  'onenote.com': 'OneNote',
  'azure.com': 'Microsoft Azure',
  'portal.azure.com': 'Azure Portal',
  'visualstudio.com': 'Visual Studio',
  'dev.azure.com': 'Azure DevOps',
  'powerbi.com': 'Power BI',
  'dynamics.com': 'Dynamics 365',
  'xbox.com': 'Xbox',
  'msn.com': 'MSN',
  'bing.com/images': 'Bing Images',
  'bing.com/maps': 'Bing Maps',
  'nuget.org': 'NuGet',
  'docs.microsoft.com': 'Microsoft Docs',
  'learn.microsoft.com': 'Microsoft Learn',
  'techcommunity.microsoft.com': 'Microsoft Tech Community',

  // Apple Services
  'apple.com': 'Apple',
  'music.apple.com': 'Apple Music',
  'podcasts.apple.com': 'Apple Podcasts',
  'books.apple.com': 'Apple Books',
  'news.apple.com': 'Apple News',
  'arcade.apple.com': 'Apple Arcade',
  'fitness.apple.com': 'Apple Fitness+',
  'developer.apple.com': 'Apple Developer',
  'support.apple.com': 'Apple Support',
  'store.apple.com': 'Apple Store',
  'itunes.apple.com': 'iTunes',

  // E-commerce
  'amazon.com': 'Amazon',
  'amazon.in': 'Amazon India',
  'amazon.co.uk': 'Amazon UK',
  'amazon.de': 'Amazon Germany',
  'amazon.co.jp': 'Amazon Japan',
  'ebay.com': 'eBay',
  'walmart.com': 'Walmart',
  'target.com': 'Target',
  'bestbuy.com': 'Best Buy',
  'costco.com': 'Costco',
  'alibaba.com': 'Alibaba',
  'aliexpress.com': 'AliExpress',
  'taobao.com': 'Taobao',
  'tmall.com': 'Tmall',
  'jd.com': 'JD.com',
  'flipkart.com': 'Flipkart',
  'myntra.com': 'Myntra',
  'ajio.com': 'AJIO',
  'nykaa.com': 'Nykaa',
  'snapdeal.com': 'Snapdeal',
  'meesho.com': 'Meesho',
  'shopsy.in': 'Shopsy',
  'etsy.com': 'Etsy',
  'wish.com': 'Wish',
  'shein.com': 'SHEIN',
  'zara.com': 'Zara',
  'hm.com': 'H&M',
  'uniqlo.com': 'Uniqlo',
  'gap.com': 'Gap',
  'nordstrom.com': 'Nordstrom',
  'macys.com': 'Macy\'s',
  'jcpenney.com': 'JCPenney',
  'kohls.com': 'Kohl\'s',
  'sephora.com': 'Sephora',
  'ulta.com': 'Ulta Beauty',
  'nike.com': 'Nike',
  'adidas.com': 'Adidas',
  'puma.com': 'Puma',
  'reebok.com': 'Reebok',
  'underarmour.com': 'Under Armour',
  'lululemon.com': 'Lululemon',
  'asos.com': 'ASOS',
  'boohoo.com': 'Boohoo',
  'fashionnova.com': 'Fashion Nova',
  'prettylittlething.com': 'PrettyLittleThing',
  'missguided.com': 'Missguided',
  'revolve.com': 'Revolve',
  'farfetch.com': 'Farfetch',
  'net-a-porter.com': 'Net-a-Porter',
  'ssense.com': 'SSENSE',
  'shopify.com': 'Shopify',
  'bigcommerce.com': 'BigCommerce',
  'woocommerce.com': 'WooCommerce',
  'squarespace.com': 'Squarespace',
  'wix.com': 'Wix',
  'weebly.com': 'Weebly',
  'magento.com': 'Magento',
  'shopee.com': 'Shopee',
  'lazada.com': 'Lazada',
  'rakuten.com': 'Rakuten',
  'newegg.com': 'Newegg',
  'overstock.com': 'Overstock',
  'wayfair.com': 'Wayfair',
  'homedepot.com': 'Home Depot',
  'lowes.com': 'Lowe\'s',
  'ikea.com': 'IKEA',
  'craigslist.org': 'Craigslist',
  'olx.com': 'OLX',
  'mercadolibre.com': 'MercadoLibre',
  'jumia.com': 'Jumia',

  // Food Delivery
  'doordash.com': 'DoorDash',
  'ubereats.com': 'Uber Eats',
  'grubhub.com': 'Grubhub',
  'postmates.com': 'Postmates',
  'seamless.com': 'Seamless',
  'deliveroo.com': 'Deliveroo',
  'justeat.com': 'Just Eat',
  'swiggy.com': 'Swiggy',
  'zomato.com': 'Zomato',
  'foodpanda.com': 'FoodPanda',
  'dunzo.com': 'Dunzo',
  'instacart.com': 'Instacart',
  'shipt.com': 'Shipt',
  'freshdirect.com': 'FreshDirect',
  'peapod.com': 'Peapod',
  'gopuff.com': 'GoPuff',
  'gorillas.io': 'Gorillas',
  'getir.com': 'Getir',
  'flink.com': 'Flink',
  'wolt.com': 'Wolt',
  'bolt.eu/food': 'Bolt Food',
  'rappi.com': 'Rappi',
  'ifood.com.br': 'iFood',
  'meituan.com': 'Meituan',
  'ele.me': 'Ele.me',

  // Travel & Transport
  'booking.com': 'Booking.com',
  'airbnb.com': 'Airbnb',
  'expedia.com': 'Expedia',
  'hotels.com': 'Hotels.com',
  'trivago.com': 'Trivago',
  'kayak.com': 'Kayak',
  'skyscanner.com': 'Skyscanner',
  'google.com/flights': 'Google Flights',
  'momondo.com': 'Momondo',
  'hopper.com': 'Hopper',
  'priceline.com': 'Priceline',
  'agoda.com': 'Agoda',
  'trip.com': 'Trip.com',
  'makemytrip.com': 'MakeMyTrip',
  'goibibo.com': 'Goibibo',
  'cleartrip.com': 'Cleartrip',
  'yatra.com': 'Yatra',
  'ixigo.com': 'Ixigo',
  'tripadvisor.com': 'TripAdvisor',
  'yelp.com': 'Yelp',
  'uber.com': 'Uber',
  'lyft.com': 'Lyft',
  'ola.com': 'Ola',
  'grab.com': 'Grab',
  'gojek.com': 'Gojek',
  'didi.com': 'DiDi',
  'bolt.eu': 'Bolt',
  'freenow.com': 'FREE NOW',
  'lime.com': 'Lime',
  'bird.co': 'Bird',
  'spin.app': 'Spin',
  'tier.app': 'TIER',
  'voi.com': 'Voi',
  'flixbus.com': 'FlixBus',
  'greyhound.com': 'Greyhound',
  'amtrak.com': 'Amtrak',
  'nationalrail.co.uk': 'National Rail',
  'irctc.co.in': 'IRCTC',
  'redbus.in': 'RedBus',
  'blablacar.com': 'BlaBlaCar',
  'rome2rio.com': 'Rome2Rio',
  'vrbo.com': 'Vrbo',
  'hostelworld.com': 'Hostelworld',
  'couchsurfing.com': 'Couchsurfing',

  // Finance & Banking
  'paypal.com': 'PayPal',
  'venmo.com': 'Venmo',
  'cash.app': 'Cash App',
  'zelle.com': 'Zelle',
  'stripe.com': 'Stripe',
  'square.com': 'Square',
  'braintreepayments.com': 'Braintree',
  'razorpay.com': 'Razorpay',
  'paytm.com': 'Paytm',
  'phonepe.com': 'PhonePe',
  'googlepay.com': 'Google Pay',
  'pay.google.com': 'Google Pay',
  'apple.com/apple-pay': 'Apple Pay',
  'samsung.com/pay': 'Samsung Pay',
  'alipay.com': 'Alipay',
  'wechatpay.com': 'WeChat Pay',
  'wise.com': 'Wise',
  'revolut.com': 'Revolut',
  'n26.com': 'N26',
  'monzo.com': 'Monzo',
  'chime.com': 'Chime',
  'robinhood.com': 'Robinhood',
  'etrade.com': 'E*TRADE',
  'fidelity.com': 'Fidelity',
  'schwab.com': 'Charles Schwab',
  'tdameritrade.com': 'TD Ameritrade',
  'vanguard.com': 'Vanguard',
  'coinbase.com': 'Coinbase',
  'binance.com': 'Binance',
  'kraken.com': 'Kraken',
  'gemini.com': 'Gemini (Crypto)',
  'crypto.com': 'Crypto.com',
  'blockchain.com': 'Blockchain.com',
  'bitcoin.com': 'Bitcoin.com',
  'metamask.io': 'MetaMask',
  'opensea.io': 'OpenSea',
  'rarible.com': 'Rarible',
  'niftygateway.com': 'Nifty Gateway',
  'uniswap.org': 'Uniswap',
  'sushiswap.com': 'SushiSwap',
  'pancakeswap.finance': 'PancakeSwap',
  'aave.com': 'Aave',
  'compound.finance': 'Compound',
  'curve.fi': 'Curve',
  'yearn.finance': 'Yearn Finance',
  'mint.com': 'Mint',
  'personalcapital.com': 'Personal Capital',
  'ynab.com': 'YNAB',
  'quickbooks.intuit.com': 'QuickBooks',
  'freshbooks.com': 'FreshBooks',
  'xero.com': 'Xero',
  'wave.com': 'Wave',
  'turbotax.intuit.com': 'TurboTax',
  'hrblock.com': 'H&R Block',
  'taxact.com': 'TaxAct',
  'creditkarma.com': 'Credit Karma',
  'nerdwallet.com': 'NerdWallet',
  'bankrate.com': 'Bankrate',
  'investopedia.com': 'Investopedia',
  'marketwatch.com': 'MarketWatch',
  'bloomberg.com': 'Bloomberg',
  'reuters.com': 'Reuters',
  'cnbc.com': 'CNBC',
  'wsj.com': 'Wall Street Journal',
  'ft.com': 'Financial Times',
  'fortune.com': 'Fortune',
  'forbes.com': 'Forbes',
  'businessinsider.com': 'Business Insider',
  'finance.yahoo.com': 'Yahoo Finance',
  'tradingview.com': 'TradingView',
  'stocktwits.com': 'StockTwits',
  'seekingalpha.com': 'Seeking Alpha',
  'morningstar.com': 'Morningstar',
  'zacks.com': 'Zacks',
  'tipranks.com': 'TipRanks',

  // News & Media
  'bbc.com': 'BBC',
  'bbc.co.uk': 'BBC UK',
  'cnn.com': 'CNN',
  'foxnews.com': 'Fox News',
  'msnbc.com': 'MSNBC',
  'nytimes.com': 'New York Times',
  'washingtonpost.com': 'Washington Post',
  'theguardian.com': 'The Guardian',
  'usatoday.com': 'USA Today',
  'latimes.com': 'Los Angeles Times',
  'chicagotribune.com': 'Chicago Tribune',
  'huffpost.com': 'HuffPost',
  'buzzfeed.com': 'BuzzFeed',
  'buzzfeednews.com': 'BuzzFeed News',
  'vice.com': 'Vice',
  'vox.com': 'Vox',
  'theatlantic.com': 'The Atlantic',
  'newyorker.com': 'The New Yorker',
  'wired.com': 'WIRED',
  'slate.com': 'Slate',
  'salon.com': 'Salon',
  'politico.com': 'Politico',
  'thehill.com': 'The Hill',
  'axios.com': 'Axios',
  'apnews.com': 'AP News',
  'upi.com': 'UPI',
  'afp.com': 'AFP',
  'aljazeera.com': 'Al Jazeera',
  'rt.com': 'RT',
  'euronews.com': 'Euronews',
  'dw.com': 'DW',
  'france24.com': 'France 24',
  'ndtv.com': 'NDTV',
  'timesofindia.indiatimes.com': 'Times of India',
  'hindustantimes.com': 'Hindustan Times',
  'indianexpress.com': 'Indian Express',
  'thehindu.com': 'The Hindu',
  'news18.com': 'News18',
  'indiatoday.in': 'India Today',
  'firstpost.com': 'Firstpost',
  'scroll.in': 'Scroll.in',
  'thewire.in': 'The Wire',
  'livemint.com': 'Mint',
  'economictimes.indiatimes.com': 'Economic Times',
  'moneycontrol.com': 'Moneycontrol',
  'techcrunch.com': 'TechCrunch',
  'theverge.com': 'The Verge',
  'arstechnica.com': 'Ars Technica',
  'engadget.com': 'Engadget',
  'gizmodo.com': 'Gizmodo',
  'mashable.com': 'Mashable',
  'cnet.com': 'CNET',
  'zdnet.com': 'ZDNet',
  'thenextweb.com': 'The Next Web',
  'venturebeat.com': 'VentureBeat',
  'recode.net': 'Recode',
  'protocol.com': 'Protocol',
  'theinformation.com': 'The Information',
  'stratechery.com': 'Stratechery',
  'hackernews.com': 'Hacker News',
  'news.ycombinator.com': 'Hacker News',
  'slashdot.org': 'Slashdot',
  'digg.com': 'Digg',
  'producthunt.com': 'Product Hunt',
  'betalist.com': 'BetaList',
  'indiehackers.com': 'Indie Hackers',

  // Sports
  'sports.yahoo.com': 'Yahoo Sports',
  'bleacherreport.com': 'Bleacher Report',
  'cbssports.com': 'CBS Sports',
  'nbcsports.com': 'NBC Sports',
  'foxsports.com': 'Fox Sports',
  'si.com': 'Sports Illustrated',
  'theathletic.com': 'The Athletic',
  'nba.com': 'NBA',
  'nfl.com': 'NFL',
  'mlb.com': 'MLB',
  'nhl.com': 'NHL',
  'mls.com': 'MLS',
  'fifa.com': 'FIFA',
  'uefa.com': 'UEFA',
  'premierleague.com': 'Premier League',
  'laliga.com': 'La Liga',
  'seriea.com': 'Serie A',
  'bundesliga.com': 'Bundesliga',
  'ligue1.com': 'Ligue 1',
  'cricbuzz.com': 'Cricbuzz',
  'espncricinfo.com': 'ESPNcricinfo',
  'bcci.tv': 'BCCI',
  'iplt20.com': 'IPL',
  'icc-cricket.com': 'ICC Cricket',
  'wwe.com': 'WWE',
  'ufc.com': 'UFC',
  'f1.com': 'Formula 1',
  'nascar.com': 'NASCAR',
  'pgatour.com': 'PGA Tour',
  'atptour.com': 'ATP Tour',
  'wtatennis.com': 'WTA Tennis',
  'olympics.com': 'Olympics',

  // Gaming
  'steam.com': 'Steam',
  'store.steampowered.com': 'Steam Store',
  'epicgames.com': 'Epic Games',
  'store.epicgames.com': 'Epic Games Store',
  'gog.com': 'GOG',
  'origin.com': 'EA Origin',
  'ea.com': 'EA',
  'ubisoft.com': 'Ubisoft',
  'playstation.com': 'PlayStation',
  'nintendo.com': 'Nintendo',
  'blizzard.com': 'Blizzard',
  'battle.net': 'Battle.net',
  'activision.com': 'Activision',
  'riotgames.com': 'Riot Games',
  'leagueoflegends.com': 'League of Legends',
  'valorant.com': 'Valorant',
  'fortnite.com': 'Fortnite',
  'minecraft.net': 'Minecraft',
  'roblox.com': 'Roblox',
  'genshin.hoyoverse.com': 'Genshin Impact',
  'pubg.com': 'PUBG',
  'callofduty.com': 'Call of Duty',
  'rockstargames.com': 'Rockstar Games',
  'socialclub.rockstargames.com': 'Rockstar Social Club',
  'bethesda.net': 'Bethesda',
  'ign.com': 'IGN',
  'gamespot.com': 'GameSpot',
  'kotaku.com': 'Kotaku',
  'polygon.com': 'Polygon',
  'pcgamer.com': 'PC Gamer',
  'eurogamer.net': 'Eurogamer',
  'destructoid.com': 'Destructoid',
  'gamesradar.com': 'GamesRadar',
  'giantbomb.com': 'Giant Bomb',
  'metacritic.com': 'Metacritic',
  'opencritic.com': 'OpenCritic',
  'howlongtobeat.com': 'HowLongToBeat',
  'speedrun.com': 'Speedrun.com',
  'nexusmods.com': 'Nexus Mods',
  'moddb.com': 'ModDB',
  'curseforge.com': 'CurseForge',
  'fandom.com': 'Fandom',
  'gamefaqs.gamespot.com': 'GameFAQs',
  'itch.io': 'itch.io',
  'indiedb.com': 'IndieDB',
  'gamejolt.com': 'Game Jolt',
  'kongregate.com': 'Kongregate',
  'newgrounds.com': 'Newgrounds',
  'miniclip.com': 'Miniclip',
  'poki.com': 'Poki',
  'crazygames.com': 'CrazyGames',
  'addictinggames.com': 'Addicting Games',
  'armor games.com': 'Armor Games',
  'coolmathgames.com': 'Cool Math Games',

  // Developer Tools
  'github.com': 'GitHub',
  'gitlab.com': 'GitLab',
  'bitbucket.org': 'Bitbucket',
  'sourceforge.net': 'SourceForge',
  'codeberg.org': 'Codeberg',
  'sr.ht': 'SourceHut',
  'replit.com': 'Replit',
  'codepen.io': 'CodePen',
  'jsfiddle.net': 'JSFiddle',
  'codesandbox.io': 'CodeSandbox',
  'stackblitz.com': 'StackBlitz',
  'glitch.com': 'Glitch',
  'plnkr.co': 'Plunker',
  'pastebin.com': 'Pastebin',
  'gist.github.com': 'GitHub Gist',
  'stackoverflow.com': 'Stack Overflow',
  'stackexchange.com': 'Stack Exchange',
  'askubuntu.com': 'Ask Ubuntu',
  'serverfault.com': 'Server Fault',
  'superuser.com': 'Super User',
  'dev.to': 'DEV Community',
  'hashnode.com': 'Hashnode',
  'medium.com': 'Medium',
  'freecodecamp.org': 'freeCodeCamp',
  'codecademy.com': 'Codecademy',
  'udemy.com': 'Udemy',
  'coursera.org': 'Coursera',
  'edx.org': 'edX',
  'pluralsight.com': 'Pluralsight',
  'linkedin.com/learning': 'LinkedIn Learning',
  'treehouse.com': 'Treehouse',
  'datacamp.com': 'DataCamp',
  'leetcode.com': 'LeetCode',
  'hackerrank.com': 'HackerRank',
  'codewars.com': 'Codewars',
  'exercism.io': 'Exercism',
  'topcoder.com': 'TopCoder',
  'codeforces.com': 'Codeforces',
  'atcoder.jp': 'AtCoder',
  'spoj.com': 'SPOJ',
  'codechef.com': 'CodeChef',
  'geeksforgeeks.org': 'GeeksforGeeks',
  'tutorialspoint.com': 'TutorialsPoint',
  'w3schools.com': 'W3Schools',
  'mdn.io': 'MDN Web Docs',
  'developer.mozilla.org': 'MDN Web Docs',
  'css-tricks.com': 'CSS-Tricks',
  'smashingmagazine.com': 'Smashing Magazine',
  'alistapart.com': 'A List Apart',
  'sitepoint.com': 'SitePoint',
  'scotch.io': 'Scotch.io',
  'digitalocean.com/community': 'DigitalOcean Tutorials',
  'heroku.com': 'Heroku',
  'netlify.com': 'Netlify',
  'vercel.com': 'Vercel',
  'render.com': 'Render',
  'railway.app': 'Railway',
  'fly.io': 'Fly.io',
  'cloudflare.com': 'Cloudflare',
  'pages.cloudflare.com': 'Cloudflare Pages',
  'workers.cloudflare.com': 'Cloudflare Workers',
  'aws.amazon.com': 'AWS',
  'console.aws.amazon.com': 'AWS Console',
  'azure.microsoft.com': 'Microsoft Azure',
  'digitalocean.com': 'DigitalOcean',
  'linode.com': 'Linode',
  'vultr.com': 'Vultr',
  'hetzner.com': 'Hetzner',
  'ovhcloud.com': 'OVHcloud',
  'docker.com': 'Docker',
  'hub.docker.com': 'Docker Hub',
  'kubernetes.io': 'Kubernetes',
  'terraform.io': 'Terraform',
  'ansible.com': 'Ansible',
  'jenkins.io': 'Jenkins',
  'circleci.com': 'CircleCI',
  'travis-ci.com': 'Travis CI',
  'github.com/actions': 'GitHub Actions',
  'npmjs.com': 'npm',
  'yarnpkg.com': 'Yarn',
  'pnpm.io': 'pnpm',
  'pypi.org': 'PyPI',
  'rubygems.org': 'RubyGems',
  'crates.io': 'crates.io',
  'packagist.org': 'Packagist',
  'mvnrepository.com': 'Maven Repository',
  'cocoapods.org': 'CocoaPods',
  'pub.dev': 'pub.dev',
  'sentry.io': 'Sentry',
  'datadog.com': 'Datadog',
  'newrelic.com': 'New Relic',
  'splunk.com': 'Splunk',
  'elastic.co': 'Elastic',
  'grafana.com': 'Grafana',
  'prometheus.io': 'Prometheus',
  'pagerduty.com': 'PagerDuty',
  'opsgenie.com': 'Opsgenie',
  'statuspage.io': 'Statuspage',
  'postman.com': 'Postman',
  'insomnia.rest': 'Insomnia',
  'swagger.io': 'Swagger',
  'apiary.io': 'Apiary',
  'readme.io': 'ReadMe',
  'stoplight.io': 'Stoplight',

  // Productivity & Collaboration
  'notion.so': 'Notion',
  'airtable.com': 'Airtable',
  'asana.com': 'Asana',
  'trello.com': 'Trello',
  'monday.com': 'Monday.com',
  'clickup.com': 'ClickUp',
  'basecamp.com': 'Basecamp',
  'wrike.com': 'Wrike',
  'smartsheet.com': 'Smartsheet',
  'teamwork.com': 'Teamwork',
  'todoist.com': 'Todoist',
  'ticktick.com': 'TickTick',
  'any.do': 'Any.do',
  'rememberthemilk.com': 'Remember The Milk',
  'habitica.com': 'Habitica',
  'evernote.com': 'Evernote',
  'bear.app': 'Bear',
  'ulysses.app': 'Ulysses',
  'obsidian.md': 'Obsidian',
  'roamresearch.com': 'Roam Research',
  'logseq.com': 'Logseq',
  'remnote.com': 'RemNote',
  'craft.do': 'Craft',
  'supernotes.app': 'Supernotes',
  'dropbox.com': 'Dropbox',
  'dropbox.com/paper': 'Dropbox Paper',
  'box.com': 'Box',
  'mega.nz': 'MEGA',
  'pcloud.com': 'pCloud',
  'sync.com': 'Sync.com',
  'icedrive.net': 'Icedrive',
  'internxt.com': 'Internxt',
  'tresorit.com': 'Tresorit',
  'spideroak.com': 'SpiderOak',
  'figma.com': 'Figma',
  'sketch.com': 'Sketch',
  'adobe.com/xd': 'Adobe XD',
  'invisionapp.com': 'InVision',
  'zeplin.io': 'Zeplin',
  'marvel.app': 'Marvel',
  'proto.io': 'Proto.io',
  'framer.com': 'Framer',
  'principle.app': 'Principle',
  'origami.design': 'Origami Studio',
  'rive.app': 'Rive',
  'lottiefiles.com': 'LottieFiles',
  'canva.com': 'Canva',
  'crello.com': 'Crello',
  'snappa.com': 'Snappa',
  'venngage.com': 'Venngage',
  'piktochart.com': 'Piktochart',
  'infogram.com': 'Infogram',
  'visme.co': 'Visme',
  'prezi.com': 'Prezi',
  'slides.com': 'Slides.com',
  'pitch.com': 'Pitch',
  'miro.com': 'Miro',
  'mural.co': 'Mural',
  'lucidchart.com': 'Lucidchart',
  'lucidspark.com': 'Lucidspark',
  'draw.io': 'draw.io',
  'app.diagrams.net': 'diagrams.net',
  'whimsical.com': 'Whimsical',
  'excalidraw.com': 'Excalidraw',
  'mindmeister.com': 'MindMeister',
  'coggle.it': 'Coggle',
  'xmind.net': 'XMind',
  'milanote.com': 'Milanote',
  'witeboard.com': 'Witeboard',
  'awwapp.com': 'AWW App',
  'conceptboard.com': 'Conceptboard',
  'stormboard.com': 'Stormboard',

  // Health & Fitness
  'fitbit.com': 'Fitbit',
  'myfitnesspal.com': 'MyFitnessPal',
  'strava.com': 'Strava',
  'nike.com/ntc': 'Nike Training Club',
  'nike.com/nrc': 'Nike Run Club',
  'peloton.com': 'Peloton',
  'classpass.com': 'ClassPass',
  'headspace.com': 'Headspace',
  'calm.com': 'Calm',
  'insight.com': 'Insight Timer',
  'tenpercent.com': 'Ten Percent Happier',
  'noom.com': 'Noom',
  'weightwatchers.com': 'WeightWatchers',
  'webmd.com': 'WebMD',
  'mayoclinic.org': 'Mayo Clinic',
  'nih.gov': 'NIH',
  'cdc.gov': 'CDC',
  'who.int': 'WHO',
  'healthline.com': 'Healthline',
  'medicalnewstoday.com': 'Medical News Today',
  'everydayhealth.com': 'Everyday Health',
  'verywellhealth.com': 'Verywell Health',
  'drugs.com': 'Drugs.com',
  'goodrx.com': 'GoodRx',
  '1mg.com': '1mg',
  'practo.com': 'Practo',
  'zocdoc.com': 'Zocdoc',
  'teladoc.com': 'Teladoc',
  'doctorondemand.com': 'Doctor On Demand',
  'amwell.com': 'Amwell',
  'mdlive.com': 'MDLive',

  // Education
  'khanacademy.org': 'Khan Academy',
  'duolingo.com': 'Duolingo',
  'babbel.com': 'Babbel',
  'rosettastone.com': 'Rosetta Stone',
  'busuu.com': 'Busuu',
  'memrise.com': 'Memrise',
  'quizlet.com': 'Quizlet',
  'anki.net': 'Anki',
  'brainly.com': 'Brainly',
  'chegg.com': 'Chegg',
  'coursehero.com': 'Course Hero',
  'studocu.com': 'StuDocu',
  'scribd.com': 'Scribd',
  'academia.edu': 'Academia.edu',
  'researchgate.net': 'ResearchGate',
  'jstor.org': 'JSTOR',
  'scholar.google.com': 'Google Scholar',
  'wikipedia.org': 'Wikipedia',
  'britannica.com': 'Britannica',
  'sparknotes.com': 'SparkNotes',
  'cliffsnotes.com': 'CliffsNotes',
  'gradesfirst.com': 'GradesFirst',
  'turnitin.com': 'Turnitin',
  'blackboard.com': 'Blackboard',
  'canvas.instructure.com': 'Canvas LMS',
  'moodle.org': 'Moodle',
  'd2l.com': 'D2L Brightspace',
  'schoology.com': 'Schoology',
  'edmodo.com': 'Edmodo',
  'kahoot.com': 'Kahoot!',
  'quizizz.com': 'Quizizz',
  'nearpod.com': 'Nearpod',
  'socrative.com': 'Socrative',
  'polleverywhere.com': 'Poll Everywhere',
  'mentimeter.com': 'Mentimeter',
  'slido.com': 'Slido',
  'classdojo.com': 'ClassDojo',
  'remind.com': 'Remind',
  'seesaw.me': 'Seesaw',
  'flipgrid.com': 'Flipgrid',
  'screencastify.com': 'Screencastify',
  'educreations.com': 'Educreations',
  'explaineverything.com': 'Explain Everything',

  // Job & Career
  'linkedin.com/jobs': 'LinkedIn Jobs',
  'indeed.com': 'Indeed',
  'glassdoor.com': 'Glassdoor',
  'monster.com': 'Monster',
  'careerbuilder.com': 'CareerBuilder',
  'ziprecruiter.com': 'ZipRecruiter',
  'dice.com': 'Dice',
  'angel.co': 'AngelList',
  'wellfound.com': 'Wellfound',
  'hired.com': 'Hired',
  'triplebyte.com': 'Triplebyte',
  'toptal.com': 'Toptal',
  'upwork.com': 'Upwork',
  'fiverr.com': 'Fiverr',
  'freelancer.com': 'Freelancer',
  'guru.com': 'Guru',
  'peopleperhour.com': 'PeoplePerHour',
  '99designs.com': '99designs',
  'designcrowd.com': 'DesignCrowd',
  'crowdspring.com': 'Crowdspring',
  'naukri.com': 'Naukri',
  'shine.com': 'Shine',
  'iimjobs.com': 'IIM Jobs',
  'timesjobs.com': 'TimesJobs',
  'freshersworld.com': 'FreshersWorld',
  'internshala.com': 'Internshala',
  'wayup.com': 'WayUp',
  'handshake.com': 'Handshake',
  'lever.co': 'Lever',
  'greenhouse.io': 'Greenhouse',
  'workday.com': 'Workday',
  'bamboohr.com': 'BambooHR',
  'gusto.com': 'Gusto',
  'adp.com': 'ADP',
  'paychex.com': 'Paychex',
  'paylocity.com': 'Paylocity',

  // Dating
  'tinder.com': 'Tinder',
  'bumble.com': 'Bumble',
  'hinge.co': 'Hinge',
  'match.com': 'Match',
  'okcupid.com': 'OkCupid',
  'pof.com': 'Plenty of Fish',
  'eharmony.com': 'eHarmony',
  'zoosk.com': 'Zoosk',
  'elitesingles.com': 'EliteSingles',
  'coffee-meets-bagel.com': 'Coffee Meets Bagel',
  'happn.com': 'Happn',
  'badoo.com': 'Badoo',
  'grindr.com': 'Grindr',
  'her.app': 'HER',

  // Real Estate
  'zillow.com': 'Zillow',
  'realtor.com': 'Realtor.com',
  'redfin.com': 'Redfin',
  'trulia.com': 'Trulia',
  'apartments.com': 'Apartments.com',
  'rent.com': 'Rent.com',
  'zumper.com': 'Zumper',
  'hotpads.com': 'HotPads',
  'rightmove.co.uk': 'Rightmove',
  'zoopla.co.uk': 'Zoopla',
  '99acres.com': 'Housing.com',
  'magicbricks.com': 'MagicBricks',
  'commonfloor.com': 'CommonFloor',
  'nobroker.in': 'NoBroker',
  'squareyards.com': 'Square Yards',
  'proptiger.com': 'PropTiger',

  // Music & Audio
  'spotify.com': 'Spotify',
  'open.spotify.com': 'Spotify Web Player',
  'soundcloud.com': 'SoundCloud',
  'pandora.com': 'Pandora',
  'tidal.com': 'Tidal',
  'deezer.com': 'Deezer',
  'music.youtube.com': 'YouTube Music',
  'music.amazon.com': 'Amazon Music',
  'audible.com': 'Audible',
  'anchor.fm': 'Anchor',
  'podbean.com': 'Podbean',
  'buzzsprout.com': 'Buzzsprout',
  'spreaker.com': 'Spreaker',
  'transistor.fm': 'Transistor',
  'overcast.fm': 'Overcast',
  'pocketcasts.com': 'Pocket Casts',
  'castbox.fm': 'Castbox',
  'stitcher.com': 'Stitcher',
  'iheart.com': 'iHeartRadio',
  'tunein.com': 'TuneIn',
  'radio.com': 'Radio.com',
  'last.fm': 'Last.fm',
  'genius.com': 'Genius',
  'lyrics.com': 'Lyrics.com',
  'azlyrics.com': 'AZLyrics',
  'musixmatch.com': 'Musixmatch',
  'songkick.com': 'Songkick',
  'bandsintown.com': 'Bandsintown',
  'bandcamp.com': 'Bandcamp',
  'discogs.com': 'Discogs',
  'allmusic.com': 'AllMusic',
  'pitchfork.com': 'Pitchfork',
  'rollingstone.com': 'Rolling Stone',
  'billboard.com': 'Billboard',
  'nme.com': 'NME',
  'consequence.net': 'Consequence',
  'stereogum.com': 'Stereogum',
  'thequietus.com': 'The Quietus',
  'splice.com': 'Splice',
  'landr.com': 'LANDR',
  'distrokid.com': 'DistroKid',
  'tunecore.com': 'TuneCore',
  'cdbaby.com': 'CD Baby',
  'reverbnation.com': 'ReverbNation',

  // Photography & Design
  'unsplash.com': 'Unsplash',
  'pexels.com': 'Pexels',
  'pixabay.com': 'Pixabay',
  'shutterstock.com': 'Shutterstock',
  'gettyimages.com': 'Getty Images',
  'istockphoto.com': 'iStock',
  'adobe.com/stock': 'Adobe Stock',
  '500px.com': '500px',
  'flickr.com': 'Flickr',
  'smugmug.com': 'SmugMug',
  'photobucket.com': 'Photobucket',
  'imgur.com': 'Imgur',
  'giphy.com': 'GIPHY',
  'tenor.com': 'Tenor',
  'imgflip.com': 'Imgflip',
  'remove.bg': 'Remove.bg',
  'cleanup.pictures': 'Cleanup.pictures',
  'photopea.com': 'Photopea',
  'pixlr.com': 'Pixlr',
  'fotor.com': 'Fotor',
  'befunky.com': 'BeFunky',
  'ipiccy.com': 'iPiccy',
  'lunapic.com': 'LunaPic',
  'photofunia.com': 'PhotoFunia',
  'fotojet.com': 'FotoJet',
  'picmonkey.com': 'PicMonkey',
  'stickermule.com': 'Sticker Mule',
  'printful.com': 'Printful',
  'printify.com': 'Printify',
  'redbubble.com': 'Redbubble',
  'society6.com': 'Society6',
  'teespring.com': 'Spring',
  'zazzle.com': 'Zazzle',
  'vistaprint.com': 'VistaPrint',
  'moo.com': 'MOO',
  'dribbble.com': 'Dribbble',
  'behance.net': 'Behance',
  'artstation.com': 'ArtStation',
  'deviantart.com': 'DeviantArt',
  'creativemarket.com': 'Creative Market',
  'graphicriver.net': 'GraphicRiver',
  'envato.com': 'Envato',
  'elements.envato.com': 'Envato Elements',
  'themeforest.net': 'ThemeForest',
  'codecanyon.net': 'CodeCanyon',
  'videohive.net': 'VideoHive',
  'audiojungle.net': 'AudioJungle',
  'photodune.net': 'PhotoDune',
  '3docean.net': '3DOcean',
  'flaticon.com': 'Flaticon',
  'iconfinder.com': 'Iconfinder',
  'icons8.com': 'Icons8',
  'thenounproject.com': 'The Noun Project',
  'fontawesome.com': 'Font Awesome',
  'iconmonstr.com': 'iconmonstr',
  'simpleicons.org': 'Simple Icons',
  'feathericons.com': 'Feather Icons',
  'heroicons.com': 'Heroicons',
  'lucide.dev': 'Lucide',
  'tabler-icons.io': 'Tabler Icons',
  'boxicons.com': 'Boxicons',
  'phosphoricons.com': 'Phosphor Icons',
  'fontsquirrel.com': 'Font Squirrel',
  'dafont.com': 'DaFont',
  '1001fonts.com': '1001 Fonts',
  'fontspace.com': 'FontSpace',
  'myfonts.com': 'MyFonts',
  'fonts.adobe.com': 'Adobe Fonts',
  'fontshare.com': 'Fontshare',
  'atipofoundry.com': 'Atipo Foundry',
  'colophonfoundry.org': 'Colophon',
  'typewolf.com': 'Typewolf',
  'fontpair.co': 'FontPair',
  'coolors.co': 'Coolors',
  'colorhunt.co': 'Color Hunt',
  'color.adobe.com': 'Adobe Color',
  'colormind.io': 'Colormind',
  'paletton.com': 'Paletton',
  'colorspace.r-c.ai': 'ColorSpace',
  'happyhues.co': 'Happy Hues',
  'colordesigner.io': 'ColorDesigner',
  'khroma.co': 'Khroma',
  'muzli-colors.com': 'Muzli Colors',

  // Government & Utilities
  'irs.gov': 'IRS',
  'ssa.gov': 'Social Security',
  'usa.gov': 'USA.gov',
  'benefits.gov': 'Benefits.gov',
  'usps.com': 'USPS',
  'ups.com': 'UPS',
  'fedex.com': 'FedEx',
  'dhl.com': 'DHL',
  'bluedart.com': 'BlueDart',
  'delhivery.com': 'Delhivery',
  'dtdc.in': 'DTDC',
  'indiapost.gov.in': 'India Post',
  'passportindia.gov.in': 'Passport Seva',
  'incometax.gov.in': 'Income Tax India',
  'gst.gov.in': 'GST Portal',
  'digilocker.gov.in': 'DigiLocker',
  'umang.gov.in': 'UMANG',
  'cowin.gov.in': 'CoWIN',
  'aarogyasetu.gov.in': 'Aarogya Setu',
  'epfindia.gov.in': 'EPFO',
  'uidai.gov.in': 'UIDAI Aadhaar',

  // Miscellaneous
  'weather.com': 'The Weather Channel',
  'accuweather.com': 'AccuWeather',
  'wunderground.com': 'Weather Underground',
  'timeanddate.com': 'Time and Date',
  'worldtimebuddy.com': 'World Time Buddy',
  'xe.com': 'XE Currency',
  'oanda.com': 'OANDA',
  'calculator.net': 'Calculator.net',
  'symbolab.com': 'Symbolab',
  'mathway.com': 'Mathway',
  'desmos.com': 'Desmos',
  'geogebra.org': 'GeoGebra',
  'speedtest.net': 'Speedtest',
  'fast.com': 'Fast.com',
  'downdetector.com': 'Downdetector',
  'isitdownrightnow.com': 'Is It Down Right Now',
  'archive.org': 'Internet Archive',
  'web.archive.org': 'Wayback Machine',
  'wikihow.com': 'wikiHow',
  'howstuffworks.com': 'HowStuffWorks',
  'instructables.com': 'Instructables',
  'diy.com': 'DIY',
  'houzz.com': 'Houzz',
  'goodreads.com': 'Goodreads',
  'librarything.com': 'LibraryThing',
  'storygraph.com': 'The StoryGraph',
  'imdb.com': 'IMDb',
  'rottentomatoes.com': 'Rotten Tomatoes',
  'letterboxd.com': 'Letterboxd',
  'justwatch.com': 'JustWatch',
  'tvtime.com': 'TV Time',
  'trakt.tv': 'Trakt',
  'simkl.com': 'Simkl',
  'myanimelist.net': 'MyAnimeList',
  'anilist.co': 'AniList',
  'kitsu.io': 'Kitsu',
  'anime-planet.com': 'Anime-Planet',
  'mangadex.org': 'MangaDex',
  'mangaplus.shueisha.co.jp': 'MANGA Plus',
  'webtoon.com': 'WEBTOON',
  'tapas.io': 'Tapas',
  'comixology.com': 'ComiXology',
  'marvel.com': 'Marvel',
  'dc.com': 'DC Comics',
  'imagecomics.com': 'Image Comics',
};

export function getPageNameFromUrl(url: string): string {
  if (!url || url === 'Unknown' || url === 'Unknown page' || url === 'Window lost focus') {
    return 'Unknown Activity';
  }

  try {
    let hostname: string;
    
    if (url.startsWith('http://') || url.startsWith('https://')) {
      const urlObj = new URL(url);
      hostname = urlObj.hostname.replace(/^www\./, '').toLowerCase();
    } else {
      hostname = url.replace(/^www\./, '').toLowerCase();
    }

    for (const [pattern, name] of Object.entries(URL_MAPPINGS)) {
      if (hostname === pattern || hostname.endsWith('.' + pattern) || hostname.includes(pattern)) {
        return name;
      }
    }

    const pathParts = url.includes('/') ? url.split('/') : [];
    for (const part of pathParts) {
      for (const [pattern, name] of Object.entries(URL_MAPPINGS)) {
        if (part.includes(pattern)) {
          return name;
        }
      }
    }

    return hostname || 'Unknown Website';
  } catch {
    return 'Unknown Activity';
  }
}
